import React from 'react'
import './Terms.css'
import Footer from './Footer'
function TermandCondition() {
  return (
    <div className='termbox'>
        <a href='/'>Home</a>
        <h1><b>Terms and Conditions</b></h1>
        <div className='box1'>
            <h4><b>1. Acceptance of Terms.</b></h4>
            <p> If you are not in agreement with these Terms or the terms of our  <a href='privacy' style={{fontSize:'14px',color:'blue'}}>PrivacyPolicy</a>, please discontinue your use of the site. Your use of the site operates as express consent to these Terms. Some of parts of our Services may have additional terms and conditions. Please read these additional terms and conditions before using such services. No additional terms and conditions or any other terms will serve to replace or change these Terms, unless otherwise specified.</p>
        </div><br/>
        <div className='box2'>
            <h4><b>2. Updates.</b></h4>
            <p>We strive to provide the best experience to our users, and as such, these Terms may be revised and changed by posting updated Terms on the Site. We will post updated terms on the Site, this will serve as your notification. You should visit the Site regularly in order to keep updated on the latest Terms. If you continue using the Services after the updates, your continued use will be construed as an express acceptance of the revisions. Some elements of ResumeNerd may only be offered in the desktop version of the Site and may not be, for example, available in the mobile version.

</p></div><br/>
        <div className='box1'>
            <h4><b>3. Legal Capacity.</b></h4>
            <p>ResumeNerd is a general audience website for the use of adults. By using the Services you warrant that you have the requisite legal capacity to enter into the agreement contained in these Terms. Legal capacity requires you be (a) of sufficient age (16 years or older) or (b) the age of majority in your place of residency and/or (c) lawfully able to enter into contracts. You must also have mental capacity and have to be entitled to be legally bound in contract like these Terms. If you are not legally able to enter into contracts, you cannot use the Site at any time or submit any information to us.</p>
        </div><br/>
        
        <div className='box2'>
            <h4><b>4.Accuracy of Your Information.</b></h4>
            <p>Access and use of our Services may require you to provide registration details. As a condition of use, the details you provide must be correct, current and complete. If at any time we believe that your details are incorrect or incomplete, we have the right to refuse you access to the Services. We also reserve the right to cancel or suspend your account or access.</p>
        </div><br/>

        <div className='box1'>
            <h4><b>5. Privacy Notice.</b></h4>
            <p > Your privacy is important to us. To better protect your privacy, we have created a  <a href='privacy' style={{fontSize:'14px',color:'blue'}}>PrivacyPolicy</a> with information on our online information practices and the choices you can make regarding how we collect and use your information.</p>
        </div><br/>

        <div className='box2'>
            <h4><b>6. Service.</b></h4>
            <p><ol>
                <li> You are granted a right to use the Services, subject to these Terms. The right to use the Services belongs to you as an individual (not a partnership, corporate or other business entity), and is non-transferable. To have access to our Services, you must have access to the World Wide Web (the “Web”) and therefore pay any fees associated with that access. ResumeNerd will not provide any equipment necessary to connect to the Web, including but not limited to, a computer, modem, mobile device, table or other accessibility device.</li><br/>
                <li>  As part of ResumeNerd’s services you may have access to automatic tools that will use algorithms to provide options according to the skills, experience and education you have provided. These are only meant to offer options that could interest you in your job search. Even when it appears that you have matched with a job, the qualification is finally decided solely by the hiring authority (“Employer”) taking into consideration the particular skills relevant and appropriate for the job. Our tools do not guarantee a job or a job offer or any further communication or action by an Employer. We do not guarantee you will get contacted or employed even when the system automatically states that you are a match, provides a perfect score or a top rank.</li><br/>
                <li>  When you open an account with us you will be able to upload documents to our system as part of the resume and cover letter creation process. For your convenience, these documents will remain stored as long as you have an account with us. If you would like to delete your account please send an email to  <a href="mailto:asglobalsofttech23@gmail.com"> asglobalsofttech23.com</a> </li><br/>
                <li>  ResumeNerd may provide suggestions or information regarding your job search process, however you agree that it is your responsibility to determine and define what best applies to your job-hunting process in accordance with your needs and expectations.</li><br/>
                <li>  From time to time ResumeNerd may use or refer to trademarks and/or trade names that are property of third parties. This use is not meant to represent ResumeNerd affiliation with these third parties and appear for identification purposes only.</li><br/>
                <li>  These Terms and your rights to access, download from, and use the Service are subject to immediate termination, without notice, (i) if you breach (or ResumeNerd reasonably suspects that you have breached) any provision of these Terms; or (ii) upon ResumeNerd’s discontinuation of its dissemination or support of the Service. If such termination without notice is expressly prohibited by applicable law, then such termination will occur upon notice of any such breach. Upon termination, you must cease all use of the Service. If ResumeNerd terminates these Terms, or suspends your account for any of the reasons set forth in these Terms, ResumeNerd shall have no liability or responsibility to you, and ResumeNerd will not refund any amounts that you may have previously paid. </li><br/>
                </ol>  </p>      </div><br/>
        <div className='box1'>
            <h4><b>7. Social Sharing Option; Resume Posting Services, and other Services</b></h4>
            <p>ResumeNerd provides various options to help you share your resume with third parties. By making use of ResumeNerds’s sharing or posting services you agree that ResumeNerd will use proprietary web-based information gathering tools to enable you to share your resume with third parties. You further agree that the wording and interpretation of your information for purposes of resume sharing services will be in ResumeNerd’s sole discretion and ResumeNerd may be able to take any decisions to include, not include or rephrase information about you as part of the resume sharing services. By using our Resume Sharing Services you’re accepting full and total responsibility for the actions ResumeNerd performs on your behalf and at your request as if you had performed those actions yourself. This includes accepting terms of use and privacy policies and other policies that ResumeNerd might be prompted to accept on third party sites prior to sharing your resume. ResumeNerd may also offer job posting and resume submission features as part of the Site in certain locations or jurisdictions. There features may only be used by individuals seeking employment and/or career information. You may check the third-party sites where we may post your information to see their terms of use and <a href='privacy' style={{fontSize:'14px',color:'blue'}}>PrivacyPolicy</a> . You further acknowledge, agree and consent that you will take full responsibility and are personally liable for any consequences arising from your use of the Social Sharing or Resume Posting Services.<br/><br/>
You may have the option to also create and manage your own website through ResumeNerd. Once you sign up this service you agree for ResumeNerd to make use of the information you provide and make it publicly available for anyone, including third parties. You may unpublish your website at any time through your settings. Also, if your account is deleted, your website may no longer be visible. ResumeNerd will not be able to delete any previously accessed, stored, and/or copied information by third parties. Note that by publishing your information in your own website, you might receive communications by third parties either directly or through ResumeNerd. Any communications with third parties prompted by the use of your publicly available contact information is AT YOUR OWN RISK and ResumeNerd bears no responsibility. You are further solely responsible for the security of the information shared. You herby irrevocably waive any claim against ResumeNerd with respect to such communications. ResumeNerd does not provide any warranty that you will receive job alerts, communications or career opportunities by publishing your information on this website.<br/><br/>

ResumeNerd will not be liable for any loss or damage (direct, indirect, punitive, actual, consequential, incidental, special, exemplary or otherwise) resulting from any use or misuse of the services provided under this section. To the extent permitted by applicable law, you agree to indemnify and hold harmless ResumeNerd and its officers, directors, employees, agents, distributors, and affiliates from and against any and all claims, demands, liabilities, costs or expenses, including reasonable legal fees, resulting from your use of the services described in this Section.</p>
        </div><br/>
        <div className='box2'>
            <h4><b>8. Intellectual Property Rights and Trademarks and Copyrights.</b></h4>
            <p>You are allowed to use the Services and any user interphase component or content herein subject to these Terms (the “Material”). Any change or use of the Material that is not explicitly allowed in these Terms will be a violation of Copyright or Trademark law and is strictly prohibited.<br/><br/>

The Service contains and/or embodies trade secrets, patented (and/or patent pending) inventions among other proprietary material and intellectual property of ResumeNerd and/or its licensors. All title and ownership rights in the Service, including but not limited to all Material and any and all copies of the Service, remain with ResumeNerd and its licensors at all times, as may be applicable. As an exception, you may copy, access, download and display Material and content displayed on the Services, as long as it is for non-commercial, personal, entertainment use on only one computer and all copyright and trademark notices are kept intact. Otherwise, the Material and content may not be copied, reproduced, republished, displayed, distributed, licensed or used in any other way without the authorization of ResumeNerd. You may not decompile, reverse engineer, disassemble or reduce the code used on or as part of the Service in order to examine the construction or copy the Services and products.</p>
        </div><br/>
        <div className='box1'>
            <h4><b>9.Your Use of Our Material.</b></h4>
            <p>You are allowed to use the Services and any user interphase component or content herein subject to these Terms (the “Material”). Any change or use of the Material that is not explicitly allowed in these Terms will be a violation of Copyright or Trademark law and is strictly prohibited.<br/><br/>
            The Service contains and/or embodies trade secrets, patented (and/or patent pending) inventions among other proprietary material and intellectual property of ResumeNerd and/or its licensors. All title and ownership rights in the Service, including but not limited to all Material and any and all copies of the Service, remain with ResumeNerd and its licensors at all times, as may be applicable. As an exception, you may copy, access, download and display Material and content displayed on the Services, as long as it is for non-commercial, personal, entertainment use on only one computer and all copyright and trademark notices are kept intact. Otherwise, the Material and content may not be copied, reproduced, republished, displayed, distributed, licensed or used in any other way without the authorization of ResumeNerd. You may not decompile, reverse engineer, disassemble or reduce the code used on or as part of the Service in order to examine the construction or copy the Services and products.</p>
        </div><br/>
        <div className='box2'>
            <h4><b>10. User and Service Forums.</b></h4>
            <p>The expressions, materials, information and opinions expressed on our Forums (i.e. bulletin boards, chat rooms and community pages) (the “Forums”) are not those of ResumeNerd. ResumeNerd cannot monitor or take responsibility for the content of the Forums. ResumeNerd may remove or modify content on Forums at any time in ResumeNerd’s sole discretion, but has no obligation to do so. Use of the Forums is at your own risk, and will be subject to the disclaimers and limitations of liability stated below</p>
        </div><br/>
        <div className='box1'>
            <h4><b>11. Requested Submissions.</b></h4>
            <p>Some areas of the Services may request submissions from you in order to improve our offerings through promotions, surveys or other means. You must carefully read any specific rules or terms that govern these submissions, since they affect your rights. If there are no additional terms, then these Terms will apply fully to those submissions. Any material you provide to us will not be treated as confidential. We will not pay you to use any of the submissions you make on the Services.</p>
        </div><br/>
        <div className='box2'>
            <h4><b>12. Our Use of User Provided Content.</b></h4>
            <p>Anything you provide to ResumeNerd that may or not contribute to the Services will be considered available for use, free of any obligations to you, except when additional terms state otherwise. Under no circumstances you will receive payment or any type of consideration for the use of your submissions.</p>
        
        </div><br/>
        <div className='box1'>
            <h4><b>13. User Provided Content.</b></h4>
            <p> Information you have provided or that we create for you, such as account information, resume, career and educational history, reviews, profile entries, posts, questions, career materials or other information, may not be able to be deleted once you have uploaded it. The Services include features where other members may be able to request notifications of any new public contents you publish and they may be able to comment on your comments. ResumeNerd may also use the public content in order to develop products, improve the Services, personalize site views, or market their products. If you post or upload content on the site, including personal information and resume information, or by communicating with ResumeNerd (“User Content”) you automatically and irrevocably:</p><br/>
       <p>
        <ul>
        <li>Grant and assign to ResumeNerd a royalty free, perpetual, non-exclusive, unrestricted, worldwide license to any and all rights in User Content. This includes, without limitation, copyrights, with all consents that allow for reproduction, distribution, modification, publication and any other use by ResumeNerd or third party authorized by ResumeNerd, by any means and in any media, without payment or any reference to you, and to advertise and promote such use, for the period of all these rights and any extensions, and if possible, perpetuity.</li><br/>
       <li>Waive any and all moral rights you have in the User Content which you may have in any part of the world and confirm that those rights have not been asserted.</li><br/>
       <li>Appoint ResumeNerd as your agent with full power to do any act ResumeNerd believes necessary to confirm the grant and assignment and waiver expressed above.</li><br/>
       <li>Represent and warrant that you are the owner of said User Content and are therefore entitled to enter into these Terms.</li><br/>
       <li>Represent and warrant that the User Content does not infringe on the intellectual property or privacy rights of any third parties.</li><br/>
       <li>Represent and warrant that the User Content is not subject to any obligation or limitations to you or any third parties, and that ResumeNerd will not be liable for the use or disclosure of the User Content provided.</li><br/>
       <li>If you wish to delete some of your User Content or deactivate your account you may do so by login in to your Account and click on My Settings. You agree that ResumeNerd may still retain data for use as described in our <a href='privacy' style={{fontSize:'14px',color:'blue'}}>PrivacyPolicy</a>such as logs and non-personally identifiable information about you along with an archival copy of your information, which is not accessible by you or third parties within the Site but may be used for internal and legitimate business purposes. Some of the User Content that we create for you may not be able to be deleted once uploaded to the extent permitted by applicable law. ResumeNerd has no obligation to maintain any Account you open and may delete it if you violate these Terms as determined in ResumeNerd’s sole and absolute discretion.</li><br/>
       <li>ResumeNerd takes no responsibility for any material created or accessible on or through the Site and is not obligated to monitor it, but reserves the right to do so. ResumeNerd does not endorse any User Content submitted to the Site by any user or other licensor, or any opinion, recommendation, or advice expressed therein.<b> ResumeNerd expressly disclaims any and all liability in connection with User Content.</b></li><br/>
       <li>You acknowledge that ResumeNerd has no obligation to pre-screen User Content, although ResumeNerd reserves the right in its sole discretion to do so and/or refuse or remove any User Content. By entering into these Terms, you hereby provide your irrevocable consent to such monitoring. You acknowledge and agree that you have no expectation of privacy concerning the transmission of your User Content, including without limitation videos, comments, any chat, text, or voice communications that may be facilitated through the Site. In the event that ResumeNerd pre-screens, refuses or removes any User Content, you acknowledge that ResumeNerd will do so for ResumeNerd’s benefit, not yours. ResumeNerd may provide you with tools to flag User Content, however, ResumeNerd makes no promises or representations regarding removal of flagged User Content.</li><br/>
       <li>ResumeNerd will remove User Content if properly notified that such User Content infringes on another’s intellectual property rights. ResumeNerd reserves the right to remove User Content without prior notice.</li>
       </ul></p>
        </div><br/>
        <div className='box2'>
            <h4><b>14. Access ResumeNerd using Credentials from Third-Party Network (“TPN”) Accounts.</b></h4>
            <p>When you access ResumeNerd using your TPN credentials you may link your TPN account and allow access to ResumeNerd. By doing this, you also:</p><br/>
            <p>
                <ol>
                    <li>Understand that You have the ability to disable the connection between your Account and your TPN accounts at any time by accessing the “Settings” section of the Site.</li><br></br>
                    <li>Represent that you are entitled to disclose your TPN account login information to ResumeNerd and/or grant ResumeNerd access to your TPN account.</li><br/>
                    <li>Understand that ResumeNerd may access, make available and store (if applicable) any information, data, text, software, music, sound, photographs, graphics, video, messages, tags and/or other materials accessible through the ResumeNerd internet properties that you have provided to and stored in your TPN account (“TPN Content”) so that it is available on and through the ResumeNerd internet properties via your Account.</li> <br/>
                    <li>Accept that depending on the TPN accounts you choose and subject to the privacy settings that you have set in such TPN accounts, information that you post to your TPN Accounts may be available on and through your Account on the ResumeNerd internet properties</li><br/>
                    <li>Understand that if the TPN account or associated service becomes unavailable or ResumeNerd’s access to such TPN account is terminated by the third-party service, then TPN content will no longer be available on and through the ResumeNerd internet properties.</li><br/>
                    </ol></p>      
        </div><br/>
        <div className='box1'>
            <h4><b>15. Charges, Payments/Subscriptions.</b></h4>
            <p>
                <ul>
                    <li>You agree to pay for all Services that are not obtained by means of a special promotional code offered to you by ResumeNerd for “free”. We offer additional premium services for a fee, either on a one-time (prepaid) or a subscription basis (recurring charges). You may be asked during the purchase process to provide your credit card, bank account or ”e-wallet” information (your “payment instrument”). You agree that ResumeNerd’s third party providers may store your payment instrument information, always in compliance with the highest security standards (PCI compliant). If you decide to purchase the additional premium services, You agree to pay the applicable fees for the services you order as they become due, including any related taxes that may apply. If a payment cannot be charged for the entire amount due, you agree that a partial amount may be charged to the payment method stored for the balance available and the remainder of the amount can be charged as a separate transaction either to the same method of payment or any other method stored in your account. You may also be subject to an additional administrative fee (non-refundable) for declined or partial payments of up to USD 2.50. You agree to reimburse ResumeNerd for any collection costs and interest accrued to collect overdue amounts. You have the option of registering your payment methods for recurring or automatic billing for some of the services offered. The billing and purchase terms for your order will be displayed on the offer page of the Services. If you choose the automatic or recurring subscription, you will be notified of the billing terms and how to stop the recurring billing on the Services.</li><br/>
                    <li>By purchasing the services on our Site you agree with the billing terms as provided specifically on the Site. Failure to make payments as they come due may result in the termination of your subscription. Depending on your location, the payment type and methods used, you may be subject to foreign exchange fees and a difference in prices based on exchange rates. Your bank may also charge foreign currency exchange fees. ResumeNerd is not responsible for any foreign transaction or currency exchange fees and will not make any compensation or reimbursement for charges imposed by you bank or credit card. ResumeNerd reserves the right to change the prices and fees for their Services at any time.</li><br/>
                    <li>ResumeNerd does not support all payment methods, currencies and locations for payment. If your payment method is a credit card and it expires, we will continue to bill that payment method and you will be responsible for all unpaid fees unless you modify your payment method in your customer dashboard or cancel your account associated with the Services.</li><br/>
                    <li>Your obligation to pay all fees will continue through the subscription period until you cancel your subscription. All applicable taxes are calculated based on the billing information you provide at the time of purchase. You may cancel your subscription at any time by going to the home page under “My Account” or contacting our Customer Service department by sending an email to  <a href="mailto:asglobalsofttech23@gmail.com"> asglobalsofttech23.com</a>. Refunds are not guaranteed. Any refunds that ResumeNerd should be made in your benefit, will be accredited on the payment instrument you designated when you first made a purchase or incurred a charge.</li><br/>
                   </ul>
            </p>          
        </div><br/>
        <p style={{marginLeft:'100px',width:'1300px'}}>EU residents: By accepting the information contained in this Terms and Conditions you also agree to receive and start using the services immediately and voluntarily lose your right to withdraw from this Terms.</p><br/>
        <div className='box2'>
            <h4><b>16. Deletion or Suspension of your Account or User Content.</b></h4>
            <p>You may make a request to have your User Content removed by contacting our Customer Service department via email to  <a href="mailto:asglobalsofttech23@gmail.com"> asglobalsofttech23.com</a>. However, User Content will only be deleted from public viewing by deleting or canceling your account, as explained above. When you request that ResumeNerd deletes your User Content, your resume and profile will no longer be public or visible to any users through the Services. Nonetheless, if any of your User Content was accessed by others before the request for deletion, we cannot delete the information from their systems. When you cancel your account or request a deletion of your User Content from the Services, ResumeNerd may retain logs and information that is not personally identifiable about you as well as an archival copy of your information which will only be accessible by ResumeNerd to be used in record keeping and internal purposes.</p>
        </div><br/>
        <div className='box1'>
            <h4><b>17. Specification of Services and Pricing; Errors.</b></h4>
            <p>ResumeNerd strives to provide the best and most accurate description of all the services offered. However, we cannot warrant that service specifications, pricing or other content are complete, accurate, reliable, current or without errors. In the event of any errors relating to the pricing or specifications, we shall have the right to refuse or cancel any orders in our sole discretion Additional terms may apply.</p>
        </div><br/>
        <div className='box2'>
            <h4><b>18. Use of Site; Content Limitations.</b></h4>
            <p>EU residents: Your Directive 2009/24/EC of 23 April 2009 statutory rights remain unaffected. With exception to the restricted acts all actions require authorization by ResumeNerd.</p><br/>
            <p>Please make responsible use of the Services. The Services and its contents may only be used for lawful purposes and in accordance with applicable laws and regulations. You are prohibited from storing, distributing or transmitting unlawful or illegal material through the Services. You also may not collect or store personal information about other users. Storing, distributing and transmitting illegal or unlawful material exposes you to criminal and/or civil liability. If you are the recipient of a third party claim that your material is unlawful, you agree that you will bear the burden of establishing its legality. You agree that all materials publicly or privately posted and transmitted on or through our Services are the sole responsibility of the sender and ResumeNerd is not responsible. You are responsible for all the materials you upload or publicly post or transmit through the Services.</p><br/>
            <p>We require that you do not post resumes, send any emails or submit through any forums, or make available anywhere on the Services, any material which in our opinion: (a) libels, defames, invades privacy, is obscene, pornographic, racist, abusive, harassing, threatening or offensive; (b) disparages, criticizes, belittles, parodies or portrays in a negative light any person appearing in the content; (c) seeks to exploit or harm children by exposing them to age inappropriate content, asking for their personally identifiable details or otherwise; (d) infringes on the intellectual property rights or any other right of any entity or person, including their copyrights, trademarks or right of publicity; (e) is in violation of any law or regulation or may be considered to do so; (f) you do not have the right to transmit under a contractual or other relationship; (g) advocates or promotes illegal activity; (h) impersonates or misrepresents your connection to an entity or person or manipulates headers or identifiers to disguise the content’s origin; (i) solicits funds, advertisers or sponsorships; (j) includes programs that have viruses, worms or Trojan horses or any computer codes, files or programs that are designed to overload, interrupt, collapse or destroy the functionality of any hardware, software or telecommunications system; (k) disrupts the normal flow of dialogue, causes a screen to scroll faster than users are able to type or affects the way other people engage in real time interactions via the Services; (l) copies pages or images on the Services without authorization; (m) are MP3 format files; (n) is a pyramid or similar scheme; (o) is data warehousing, using any web space made available as storage for large files or amounts of data linked from other websites; (p) violates policies and regulations established by ResumeNerd regarding the use of the Services and any connected websites; or (q) contain links to other websites that contain the kind of content described above.</p><br/>
            <p>Additionally, you may not remove any sponsorship banners or material inserted by ResumeNerd anywhere on the Services and you agree not to send, create or reply to “mailbombs”, which are mailing copies of a single message to multiple users or sending large or multiple messages to a single user with malicious intent. You will also not engage in spamming, which is unsolicited emailing for commercial or other purposes. You will not engage in any other activity that will produce an adverse effect on the operation and use of the Services by any person.</p><br/>
        </div><br/>
             <div className='box1'>
             <h4><b>19. Release.</b></h4>
             <p>If a dispute were to arise between you and one or more users, you release ResumeNerd and its affiliates from any claims, demands, liabilities, costs or expenses and damages, actual and consequential of every kind and nature, arising out of or in any way connected with those disputes. By entering into this release, you are expressly waiving any protections to the extent permitted by law, that would otherwise limit the coverage of this release to include only claims which you know or suspect exist at the time of your agreement to this release.</p>
          </div><br/>

          <div className='box2'>
            <h4><b>20. Disclaimer of Warranties.</b></h4>
            <p> YOU UNDERSTAND AND AGREE THAT YOUR USE OF THE SERVICE IS AT YOUR OWN SOLE RISK. THE SITE AND ALL THE MATERIALS, INFORMATION, SOFTWARE, FACILITIES, SERVICES AND OTHER CONTENT IN THE SITE ARE PROVIDED “AS IS” AND “AS AVAILABLE” WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS, IMPLIED OR COLLATERAL. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, THE SITE, RESUMENERD AND ANY SUBSIDIARIES OR AFFILIATED COMPANIES (“PROVIDER GROUP”) DISCLAIM ALL WARRANTIES AND CONDITIONS, EXPRESS IMPLIED OR COLLATERAL, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. YOUR USE OF THIS SITE IS AT YOUR OWN RISK. THE PROVIDER GROUP DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THIS SITE WILL BE AVAILABLE, UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SITE OR THE SERVERS THAT MAKE THE SITE AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. THE PROVIDER GROUP DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS OR CONDITIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE MATERIAL, INFORMATION, SOFTWARE, FACILITIES, SERVICES OR OTHER CONTENT ON THE SITE OR ANY WEB SITES LINKED TO THE SITE IN TERMS OF THEIR CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. THE PROVIDER GROUP MAKES NO WARRANTIES OR CONDITIONS THAT YOUR USE OF THE MATERIALS, INFORMATION, SOFTWARE, FACILITIES, SERVICE OR OTHER CONTENT IN THE SITE OR ANY WEB SITE WILL NOT INFRINGE THE RIGHTS OF OTHERS AND THE PROVIDER GROUP ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ERRORS OR OMISSIONS IN SUCH MATERIALS, INFORMATION, SOFTWARE, FACILITIES, SERVICE OR OTHER CONTENT OF THE SITE OR ANY OTHER WEB SITE. IF APPLICABLE LAW DOES NOT ALLOW THE EXCLUSION OF SOME OR ALL OF THE ABOVE IMPLIED WARRANTIES AND CONDITIONS, THE ABOVE EXCLUSIONS WILL APPLY TO YOU ONLY TO THE EXTENT PERMITTED BY APPLICABLE LAW. THE PROVIDER GROUP MAKES NO WARRANTY THAT ANY PARTICULAR PERSONAL COMPUTER, OR PORTABLE DEVICE WILL BE COMPATIBLE WITH THE SERVICE. IT IS YOUR SOLE RESPONSIBILITY TO ENSURE THAT YOUR SYSTEMS AND DEVICES WILL FUNCTION CORRECTLY WITH THE SERVICE.</p><br/>
            <p>IF YOU ARE ACCESSING THIS SITE FROM THE EUROPEAN UNION OR OTHER JURISDICTIONS THAT TO DO NOT RECOGNIZE DISCLAIMERS OF CERTAIN WARRANTIES, NOTHING IN THIS AGREEMENT SHALL EXCLUDE OR LIMIT LIABILITY FOR DEATH OR PERSONAL INJURY RESULTING FROM THE NEGLIGENCE OF EITHER PARTY OR THEIR CONTRACTORS, AGENTS OR EMPLOYEES.</p>
          </div><br/>

          <div className='box1'>
            <h4><b>21. Limitation of Liability.</b></h4>
            <p>THE PROVIDER GROUP DISCLAIMS ALL LIABILITY WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, AND DOES NOT ACCEPT ANY LIABILITY FOR ANY LOSS OR DAMAGE (DIRECT, INDIRECT, PUNITIVE, ACTUAL, CONSEQUENTIAL, INCIDENTAL, SPECIAL, EXEMPLARY OR OTHERWISE) RESULTING FROM ANY USE OR MISUSE OF, OR INABILITY TO USE, THE SITE OR ANY OTHER WEB SITE, OR THE MATERIAL, INFORMATION, SOFTWARE, PRODUCTS, FACILITIES, SERVICES OR OTHER CONTENT ON THE SITE OR ANY OTHER WEBSITE, REGARDLESS OF THE BASIS UPON WHICH LIABILITY IS CLAIMED AND EVEN IF ANY MEMBER OF THE PROVIDER GROUP HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS OR DAMAGE. WITHOUT LIMITATION, YOU (AND NOT ANY MEMBER OF THE PROVIDER GROUP) ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION IN THE EVENT OF ANY SUCH LOSS OR DAMAGE ARISING. IF APPLICABLE LAW DOES NOT ALLOW ALL OR ANY PART OF THE ABOVE LIMITATION OF LIABILITY TO APPLY TO YOU, THE LIMITATIONS WILL APPLY TO YOU ONLY TO THE EXTENT PERMITTED BY APPLICABLE LAW.</p><br/>
          <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF IMPLIED WARRANTIES OR LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO SUCH EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU. TO THE EXTENT THAT IN A PARTICULAR CIRCUMSTANCE ANY DISCLAIMER OR LIMITATION OF LIMITATION ON DAMAGES OR LIABILITY SET FORTH HEREIN IS PROHIBITED BY APPLICABLE LAW, THEN, INSTEAD OF THE PROVISIONS HEREOF IN SUCH PARTICULAR CIRCUMSTANCE, RESUMENERD SHALL BE ENTITLED TO THE MAXIMUM DISCLAIMERS AND/OR LIMITATIONS ON DAMAGES AND LIABILITY AVAILABLE AT LAW AND IN EQUITY BY SUCH APPLICABLE LAW IN SUCH PARTICULAR CIRCUMSTANCE. IN NO EVENT SHALL SUCH DAMAGES OR THE TOTAL AGGREGATE LIABILITY OF RESUMENERD EXCEEDS THE FEES PAID BY YOU IN THE PRECEDING TWELVE (12) MONTHS OR TEN AMERICAN DOLLARS (USD $10), WHICHEVER IS GREATER.</p>
          </div><br/>

          <div className='box2'>
            <h4><b>22. US Residents: Binding Arbitration Agreement; Foreign Citizens; Limitation and No Class Relief; EU Residents: Out-of-court dispute resolution notification.</b></h4>
          <p> PLEASE TAKE THE TIME TO CAREFULLY REVIEW THE FOLLOWING SECTION AS IT CONTAINS IMPORTANT INFORMATION THAT MAY IMPACT YOUR LEGAL RIGHTS AND RESPONSIBILITIES, INCLUDING YOUR ABILITY TO FILE A LAWSUIT IN COURT AND HAVE A JURY CONSIDER YOUR CLAIMS. BOTH YOU AND ResumeNerd HAVE AGREED TO ENGAGE IN MANDATORY, INDIVIDUAL, BINDING ARBITRATION, AND HAVE WAIVED CLASS ACTION PROCEDURES.</p><br/>
          <p> Applicability of Dispute Resolution; Arbitration Agreement. You and ResumeNerd agree, except as provided below, that any allegation, claim, controversy, or dispute related to the Terms, ResumeNerd’s services, or products, including access and use (or lack thereof) (collectively “Dispute”), will be resolved exclusively through final, binding, and individual arbitration, not in court (except disputes within the jurisdiction of a small claims court consistent with the jurisdictional and dollar limits that may apply, as long as it is an individual dispute and not a class action). This includes any and all Disputes arising based in contract, warranty, tort, statute, regulation, ordinance, or any other legal theory or equitable basis, shall be resolved exclusively through final, binding, and individual arbitration, rather than in Court proceedings. Both Parties agree to waive any right to a jury trial and agree to only bring claims individually, not as part of any class or representative proceeding. To be clear: the term “Dispute” shall be given the broadest reasonable interpretation under the law.</p><br/>
          <ul><p>
            <li>(i)      <b>Arbitration Process.</b>   If the Dispute is not resolved informally, the arbitration shall be administered JAMS. Streamlined Arbitration Rules and Procedures (the “JAMS Rules”) (those rules are to be incorporated by reference into this section, and as of the date of these Terms), using the English language and heard by a single, neutral arbitrator on an individual basis with no class relief. Either Party may commence arbitration proceedings upon completion of the Informal Dispute Resolution Process described in Section 22(b). In the even that JAMS is unavailable for a valid reason, the American Arbitration Association (AAA) shall govern the process. In addition to and notwithstanding the terms state above, You and ResumeNerd agree that the following will apply to your disputes:</li><br/>
                      <ul><p>
                         <li> (a).  The arbitrator, and not any federal, state, or local court or agency, shall have the exclusive authority to resolve any Dispute of any kind between you and ResumeNerd arising under or relating to the formation of this agreement including any claim in regards to its scope, interpretation, applicability, or the enforceability of this agreement to arbitrate (or any part of it), or of these Terms, including, but not limited to, any allegation, claim, controversy or Dispute (except as specifically detailed below) that all or any part of the provisions of this agreement to arbitrate or the Terms is void, invalid, or voidable.</li><br/>
                         <li> (b).  You and We, each agree that any disagreement about whether any portion of this Section 22 are arbitrable or whether it applies to the Dispute, both you and ResumeNerd agree that the arbitrator shall decide that Dispute.</li><br/>
                         <li> (c).  The arbitrator will not have the authority or power to conduct any form of class or collective arbitration, nor join or consolidate Disputes by or for individuals;</li><br/>
                         <li> (d).  Both you and ResumeNerd understand, agree and hereby irrevocably waive any right to sue or go to court (other than small claims court as provided below) to assert of defend our rights, except as detailed below.</li><br/>
                         <li> (e).  Both you and ResumeNerd, agree that any issue concerning the validity of the class action waiver contained in this arbitration agreement must be decided by a court of competent jurisdiction, and the arbitrator does not have the authority to consider the validity of the class action waiver.</li><br/>
                        </p> </ul>
                 <p>Unless both Parties agree otherwise, including to conduct arbitration proceedings by phone or video call or to have the arbitrator decide the Dispute without a hearing, any arbitration brought by or against a User who resides in the United States of America shall take place in-person in said User’s hometown or in New York, unless the arbitrator determines that an alternative location would better accommodate the convenience of the parties. If any part of these arbitration rules is found to be invalid or unenforceable, it won't affect the rest of the rules, except as set forth above. Only the arbitrator can decide if a dispute falls under these rules. If you live outside of the United States of America, any arbitration will take place in New York, NY.</p><br/>
                 <p>A neutral, sole arbitrator, pursuant to the JAMS Rules, will oversee the arbitration proceedings. Any and all arbitration proceedings under these Terms will occur individually; class arbitrations and class actions are expressly prohibited. By accepting these Terms, both you and ResumeNerd relinquish the right to a jury trial and to join, participate, or initiate any class action or class arbitration.</p><br/>
                 
            <li>(ii) <b>Informal Dispute-Resolution Process.</b>   Considering the significant expenses and the investment of time, effort, and money involved in legal disputes, both parties, you and ResumeNerd, agree to engage in an informal dispute resolution process prior to initiating any arbitration proceedings. You and we agree to use our best efforts to resolve any Disputes directly through cooperation, consultation and good faith negotiations pursuant to the following process. The party seeking to initiate arbitration must provide the other party with a written notice with a detailed description of the nature and basis of the Dispute, along with any relevant documentation, and your proposed resolution. Notices shall be sent to  <a href="mailto:asglobalsofttech23@gmail.com"> asglobalsofttech23.com</a> or the mailing address specified in the “Contact Us” section of these Terms. If we have any Dispute with you, we will send notice to you at the contact information we have on file and follow the JAMS Rules for initiating arbitration. For this reason, it is important for you to have your contact information up to date. Both you and the Provider will have a period of sixty (60) days from receipt of written notice to attempt to negotiate in good faith in an effort to resolve the Dispute informally. Neither Party, whether you or ResumeNerd, shall be compelled or obligated to resolve the Dispute under terms deemed unacceptable by either party, each in its sole discretion. Both you and ResumeNerd agree that this Informal Dispute-Resolution Process is a condition precedent which must be satisfied before the initiation of arbitration against the other party.</li>     
          <li> (iii) <b>Arbitration Costs.</b>  All arbitration costs are governed by JAMS Rules along with filing, administration, and arbitrator costs and expenses. Each party is responsible for their own attorney fees, except as otherwise awarded by the arbitrator. However, if you are able to demonstrate that these costs are significantly higher than those of a court proceeding, ResumeNerd will cover the necessary amount of any such costs and expenses the arbitrator deems necessary to ensure the arbitration does not become more costly than litigation, subject to potential reimbursement as described below.</li><br/>
                  <p> Each of us may incur attorneys’ fees during the arbitration. Each of us will bear our own legal fees and expenses. ResumeNerd will not pay your attorneys’ fees or expenses except to the extent the arbitrator deems necessary. To clarify and ensure understanding, in cases where a statute gives the prevailing party the right to recover attorneys’ fees if you prevail, the arbitrator may award attorneys’ fees in accordance with that statute. If the arbitrator finds the Dispute brought by you to arbitration to be frivolous (in whole or in part), as defined by the Federal Rule of Civil Procedure 11, or initiated with improper purpose or intent, you agree to reimburse ResumeNerd for all fees associated with the arbitration paid by us that you otherwise would have been obligated to pay pursuant to the JAMS Rules. The arbitrator, in determining whether a Dispute is frivolous (in whole or in part), will consider whether ResumeNerd either has offered adequate and full relief to you related to your claim or has already offered a full refund of the sum paid by you to ResumeNerd for services provided. If the arbitrator ultimately decides your Dispute was not frivolous, ResumeNerd will reimburse any filling fees you incurred and were not otherwise reimbursed.</p><br/>
                  <p> A judgement on the arbitration award may be enforced in any court of proper jurisdiction.</p><br/>
         <li> (iv)  Exceptions to Arbitration. Unless You and ResumeNerd agree otherwise, certain disputes, such as those within the small claims court’s consistent with the jurisdictional and dollar limits applicable (as long as the action or proceeding is brought and maintained as an individual action or proceeding and not as a class, representative, or consolidated action or proceeding) or disputes seeking only injunctive relief (including public injunctive relief), shall be pursued and resolved in a court of competent jurisdiction. Intellectual property disputes are also excluded from arbitration.</li><br/>
                <p>Any litigation in court of the aforementioned types of Disputes (except for small claims court actions) may be initiated only in a federal or state court located within the jurisdiction of New York, NY. Both you and ResumeNerd each consent to the jurisdiction of those courts for such purposes. Regardless of whether these Disputes explicitly mentioned in this Exceptions section are settled in court or through arbitration proceedings, both parties, you and ResumeNerd, acknowledge that we are bound by the class action waiver outlined in Section 22.</p><br/>
        <li>(v)  <b>Class Action and Representative Claims Waiver.</b>   To the fullest extent permitted by applicable law, you and the Provider each agree that any proceeding, whether in court or arbitration, to resolve any Dispute will be brought and conducted ONLY IN THE RESPECTIVE PARTY’S INDIVIDUAL CAPACITY AND NOT AS PART OF ANY CLASS (OR PURPORTED CLASS), CONSOLIDATED, MULTIPLE-PLAINTIFF, OR REPRESENTATIVE ACTION OR PROCEEDING (“CLASS ACTION”). You and the Provider AGREE TO WAIVE THE RIGHT TO PARTICIPATE AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS ACTION. You and the Provider EXPRESSLY WAIVE ANY ABILITY TO MAINTAIN A CLASS ACTION IN ANY FORUM (whether arbitration, court, or otherwise). If the dispute is subject to arbitration, THE ARBITRATOR WILL NOT HAVE THE AUTHORITY TO COMBINE OR AGGREGATE CLAIMS, CONDUCT A CLASS ACTION, OR MAKE AN AWARD TO ANY PERSON OR ENTITY NOT A PARTY TO THE ARBITRATION. Further, you and the Provider agree that the ARBITRATOR MAY NOT CONSOLIDATE PROCEEDINGS FOR MORE THAN ONE PERSON’S CLAIMS, AND THE ARBITRATOR MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A CLASS ACTION. For the sake of clarity, the waiver of the right to bring claims in or otherwise participate in a class, representative, or consolidated action or proceeding set forth in the class action waiver contained herein does not prevent you from seeking public injunctive relief in an individual capacity to the extent otherwise authorized by law. </li><br/>
        <p>IF ANY PART OF THIS CLASS ACTION WAIVER IS DEEMED LIMITED, VOIDED, OR UNENFORCEABLE, UNLESS MUTUALLY AGREED OTHERWISE BY THE PARTIES, THE AGREEMENT TO ARBITRATE WILL BECOME NULL AND VOID WITH RESPECT TO SUCH PROCEEDING SO LONG AS THE PROCEEDING IS PERMITTED TO PROCEED AS A CLASS ACTION. Should any court rule that the constraints of Section 22(e) are invalid or unenforceable, any putative class, private attorney general, or consolidated or representative action must be brought in a court of proper jurisdiction and not in arbitration.</p><br/>
        <li> (vi)  You may opt-out of the arbitration agreement and not be bound by the arbitration provisions set forth in these Terms. If you do so, neither party can force the other party to arbitrate. </li><br/>
            
   

     <p>This notification must be sent to ResumeNerd no later than thirty (30) days of your first acceptance of these Terms; failing to do so will require you to resolve disputes on an individual, non-class basis as specified herein. If you opt-out of only the arbitration provisions, and not also the class action waiver provision, the class action waiver still applies. You agree that you may not opt-out of only the class action waiver provision and not also the arbitration provisions. If you opt-out of the arbitration provisions, or if you opt-out of both the arbitration and the class action waiver provisions, ResumeNerd will also not be bound by them.</p><br/>

<li>(vii)<b> Additional Provisions</b>   Any significant and material changes to this binding Arbitration Agreement and/or the Class Action Waiver will be notified by updating these Terms, unless not permitted by law. Following any material change, you will have thirty (30) days to opt-out of the revised arbitration provisions or class action waiver, consistent with the terms herein. Except for the class action waiver provision mentioned above, if any part of these arbitration provisions is found to be unenforceable or invalid, the remaining sections will remain in effect. Aside from the class action waiver, as described above, only the arbitrator has the authority to determine the scope, validity, or enforceability of this binding Arbitration Agreement, including whether a Dispute is subject to arbitration under this Agreement.</li><br/>
<p>If any portion of the arbitration agreement and/or class action waiver in this Section 22 is for any reason held to be unlawful, or for any reason unenforceable, you agree that any litigation against us (except for actions in small claims court) may be commenced only in a federal or state court located in New York, NY, and both you and ResumeNerd each consent to the jurisdiction of those courts for such purposes. Should any part of these Terms and Conditions is found by an arbitrator or court of competent jurisdiction to be invalid, unlawful, void, or unenforceable, you agree that, unless it materially affects the entire intent and purpose of these Terms and Conditions, the invalidity, voidness, or unenforceability shall affect neither the validity of these Terms and Conditions nor the remaining provisions herein (except as set forth above with respect to the class action waiver), and the provision in question shall be deemed to be superseded by a valid, enforceable provision, or portion thereof, that most closely matches the intent and purpose of the original provisions, or portion thereof, as closely as possible.</p><br/>
<li>(viii) <b>Non-US Residents</b>    If you have any allegation or claims arises out of or relates to the Services or under these Terms, you agree to send written notice providing a reasonable description of the dispute and your proposed resolution. We will send any correspondence to the most recent contact information that you have provided ResumeNerd. If you have not provided contact information, then we have no obligation under this section. Nothing in this section will serve as a waiver from pursuing claims in the Court or another formal complaint process, for either party.</li><br/>
</p>
</ul></div><br/>

<div className='box1'>
    <h4><b>23. Indemnity.</b></h4>
    <p>You agree to indemnify and hold harmless ResumeNerd and its officers, directors, employees, agents, distributors and affiliates from and against any and all claims, demands, liabilities, costs or expenses, including reasonable legal fees, resulting from your breach of these Terms, including any of the foregoing provisions, representations, warranties or conditions, and/or from your placement or transmission of any content onto ResumeNerd’s servers, and/or from any and all use of your account.</p><br/>

</div><br/>

<div className='box2'>
    <h4><b>24. Security Measures.</b></h4>
    <p>The accounts and passwords you create on this Service are for individual use and should be kept confidential. You are responsible for the safeguarding of the account and password. ResumeNerd has the right to monitor your account and password and, in its sole discretion, request that you change it. If ResumeNerd believes that account and password are insecure, ResumeNerd will have the right to require this to be changed or terminate your account.</p>
<p>You may only register yourself or a third-party which you are legally authorized to represent. If a third-party claims that a username violates their rights, ResumeNerd may remove or reclaim that username.

</p>
</div><br/>

<div className='box1'>
<h4><b>25. Violation of Our Security Systems and Protocols.</b></h4>
<p>The use of the Services in order to compromise ResumeNerd’s security protocols or tamper with the system resources or accounts is prohibited. The use or distribution of instruments meant to compromise security is strictly prohibited. These instruments include, but are not limited to: password guessing programs, cracking tools or network probing tools. If you are involved in any such violation, ResumeNerd reserves the right to provide your details to the system administrators at other websites to be able to assist in resolving outstanding security incidents. Further, if you breach, or ResumeNerd reasonably suspects that you have breached any security protocols may terminate your account.</p>

</div><br/>

<div className='box2'>
    <h4>
        <b>26. Violations.</b>
    </h4>
    <p>
        <ul>
            <li> (a). If ResumeNerd suspects a violation to these Terms, ResumeNerd reserves the right to investigate and adopt the required actions in order to protect ResumeNerd’s interests. ResumeNerd may gather information from the alleged violator or from any other use. ResumeNerd reserves the right to suspend any user whose conduct they believe is in violation of the Terms and may remove any material from its servers that it understands are in violation of the Terms, without notice. </li><br/>
            <li> (b). ResumeNerd may edit, modify, cancel or remove permanently any material it believes, in its sole discretion, is posted in violation of the Terms. ResumeNerd may also warn, suspend or terminate users, or take any other corrective action it deems necessary.</li><br/>
            <li> (c). ResumeNerd will fully cooperate with any law enforcement or court order request regarding the identity of anyone posting emails or publishing materials that are believed to violate the Terms.</li><br/>
            <li> (d), By continuing to use these Services and accepting this agreement, you waive and hold harmless ResumeNerd and all its members from any claims resulting from any action taken by ResumeNerd or its members as a consequence of an investigation by law enforcement authorities.</li><br/>

        </ul>
    </p>
</div><br>
</br>

<div className='box1'>
    <h4><b>27. Reservation of Rights.</b></h4>
    <p>
    ResumeNerd reserves the right to, with or without notice, change or discontinue, any or all of the Services provided by ResumeNerd, temporarily or permanently. ResumeNerd also reserves the right to establish general guidelines and limitations to the use of the Services.
    </p>
</div><br/>
<div className='box2'>
    <h4><b>28. Compliance with Local Laws and Regulations.</b></h4>
    <p>ResumeNerd provides no representations or warranties that our Materials and content on the Services are appropriate or available for use outside of the Unites States. If you access the Services from a location not listed above, you do so at your own risk. To the extent that they are applicable, you are responsible for complying with any local laws. You also specifically agree to comply with any applicable law regarding the transmission of technical data exported from the United States or the country you reside in.</p><br/>
    <p>Our Data Protection Officer can be contacted by sending an email to Our Data Protection Officer can be contacted by sending an email to legal@resumenerd.com.</p>
</div><br/>

<div className='box1'>
    <h4><b>29.  Third-Party Links and Advertisements.</b></h4>
    <p>By using our Services, you may be linked to other websites on the Internet. These sites may contain information that some people may find offensive. ResumeNerd does not control these sites, and you acknowledge that ResumeNerd is not responsible for the content, legality, decency or any other aspect of these websites. The inclusion of these links on our Services does not imply an endorsement or association of any kind with ResumeNerd. ResumeNerd does not make any representations or warranties regarding the security of any information that these websites may request, and you irrevocably waive any claim against ResumeNerd regarding these websites. ResumeNerd encourages you to use your best judgment when providing sensitive information to any third party and to take whatever steps you deem necessary before providing any information to these websites.</p>
</div><br/>

<div className='box2'>
    <h4><b>30. Proprietary Online Services.</b></h4>
    <p>If you access any area of the Services that is accessed through a proprietary third-party online service, you will be subject to the rules, policies and guidelines of such proprietary third party online service.</p>
</div><br/>

<div className='box1'>
    <h4><b>31. Jurisdictional Statement.</b></h4>
    <p>The Content and Materials provided on the Service are included for the purpose of providing information on our services and products available in the United States and internationally.</p>
</div><br/>

<div className='box2'>
    <h4><b>32. Choice of Law; Conflicts of Law.</b></h4>
    <p>We want to make sure that your transaction is processed seamesly and for that purpose, we may serve you from multiple parts of the world. If your payment is processed by Candidate Trove LLC this transaction will be governed by the laws of the State of New York, USA without regard to the conflicts of law provisions of any state or jurisdiction, as they apply to agreement entered into and performed entirely within the state of New York, with exception of Section 23 (a) of these Terms, which will be interpreted in accordance with the FAA. If your payment was processed by Blue Market Pay ehf the laws of Iceland will apply. You agree that any action, claim or dispute with ResumeNerd or any Affiliate, arising out of or relating to these Terms, the Service, or your use of any of the foregoing will be brought exclusively in the court above stated. To the extent permitted by law, you hereby waive trial by jury and/or any defenses based upon the venue, the inconvenience of the forum, the lack of personal jurisdiction, the sufficiency of service of process or the like in any such action, suit or dispute.</p>
</div><br/>

<div className='box1'>
    <h4><b>33. Electronic Communications</b></h4>
    <p>You hereby consent to receive electronic communications, such as emails, from ResumeNerd and agree that all communications will satisfy any legal requirement that such communication would satisfy if it were in writing. The foregoing does not affect your statutory rights.</p>
</div><br/>

<div className='box2'>
    <h4><b>34. Entire Agreement.</b></h4>
    <p>These Terms, our <a href='privacy'>Privacy Policy </a>and payment authorization, together constitute the entire agreement between you and ResumeNerd with respect to its subject matter and supersede all prior and/or contemporaneous agreements and understandings, written or oral, between you and ResumeNerd with respect to the subject matter hereof. Except as expressly set forth herein, these Terms may not be amended, modified, or supplemented by the parties in any manner, except by a written instrument signed by an authorized officer of ResumeNerd.</p>
</div><br/>

<div className='box1'>
    <h4><b>35. Severability.</b></h4>
    <p>If any section of the Terms is found to be unlawful, void or unenforceable, that provision will be severable from the Terms and will not affect the enforceability of the remaining sections.</p>
</div><br/>

<div className='box2'>
    <h4> <b> 35. Help</b></h4>
    <p>The Services are operated by A2Z for Shelter. If you have any comments or complaints regarding the services, please send any and all communications to help@resumenerd.com or our mailing addresses at:
✔ A2Z For Shelter: 13A, Railway Mens Colony, Jothi nagar, koundampalayam, coimbatore.


For any questions regarding: i) privacy concerns please email  <a href="mailto:asglobalsofttech23@gmail.com"> asglobalsofttech23.com</a> or ii) legal matters please email  <a href="mailto:asglobalsofttech23@gmail.com"> asglobalsofttech23.com</a> or the address above.</p>

<p>you must send a written notification of your decision to opt-out the following address:</p><br/>
<p class="center-content">
  <p>AS Global Soft Tech</p>
  <p>13A, Railway Mens Colony, Jayanthi Nagar,</p>
  <p>Koundampalyam, Coimbatore - 641030</p>
  <a href="mailto:asglobalsofttech23@gmail.com">asglobalsofttech23.com</a>
</p>
</div>

<Footer/>

</div>
  )
}

export default TermandCondition